[build]
  publish = "chatbot-website"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Environment variables (set these in Netlify dashboard)
# LOGIN_USERNAME = "Dominik"
# LOGIN_PASSWORD = "DomAmic2025"